### ISSUE TITLE
multiple ports per "project"

### ISSUE THREAD

**Issue by jmls** [onixjs/core#7]
I want to check something - each micro-service requires it's own port, correct ?

So if I were to have 20 micro-services in my project, I would need to define 20 ports on the server ? 

What if I wanted to re-use a micro-service in another project ? Would that require another port ?

Sorry, a lot of questions, just trying to wrap my ancient brain round this architecture

**Comment by jonathan-casarrubias** [comment]
Hi @jmls thanks for reaching out, I'm glad this project is starting to feel alive after several months of work.

Anyway I will answer below your questions:

**I want to check something - each micro-service requires it's own port, correct ?**
Yes, each micro-service requires its own port, but beyond that, you only need to make sure that ports don't repeat, after that the only port you actually matters for end-developers is the one that serves the `OnixJS Context Schema` which by default is the port 3000.

Your client application (sdk) will internally call for the schema, and when you programmatically create **Application, Module or Component** References within your client,  the SDK already knows in which port every micro-service is located.

In other words, you won't need to manually connect to each of those ports, when using the SDK that process is completely transparent for you, and you just make sure you point the SDK to the ServiceHost port (3000, is also configurable)


`myproject/src/index.ts`
```js
const config = require('../onix.config.json');
import { HostBoot } from '@onixjs/core';
// Create a new HostBoot instance for our OnixJS Config
const boot: HostBoot = new HostBoot(config, { port: 3001 });
// Run our OnixJS Context
boot.run();
````

**So if I were to have 20 micro-services in my project, I would need to define 20 ports on the server ?**
You actually create 21 ports... 20 for your micro-services, 1 for the HostProvider.

**What if I wanted to re-use a micro-service in another project ? Would that require another port ?**
That depends on the context, if those 2 projects are completely unrelated (Different clients), then yes you would require a different port to be defined within your MicroService.

If you have 2 projects on the same server you would also have 2 ServiceHost, each of those would also require different project example: 3000, 3001

At the end if you have 200 micro-services distributed in 2 big projects in just 1 server, when building your client applications you really care for the 3000 and 3001 ports (ServiceHost ports).

```js
import { OnixClient, AppReference, ComponentReference} from "@onixjs/sdk";
// Create Client Instance
const SDK1: OnixClient = new OnixClient({ port: 3000 });
const SDK2: OnixClient = new OnixClient({ port: 3001 });
```

Then you already have access to your 200 microservices within your client applications without actually caring for their ports. Similar to what we already have used to.

As you can see I have been trying to address the ports management issues, to make it easier to work... I have also thought in automatically assign those ports to MicroServices, but I need to think in the smartest approach possible, to avoid inconsistencies when scaling to multiple servers, I need to make sure that instances from the same micro-service in different servers use the same port.

And for that reason, for now, I'm asking you guys to define the port for each micro-service because that way I can guarantee scalability, and in return I'm giving a really transparent management on the client side through the `OnixJS Context Schema`.

Thanks for your questions, any comment or further questions I'll be glad to clarify.

Regards,
Jon

**Comment by jmls** [comment]
Thanks for the insight. Does each micro-service live on the same machine then ? We work almost exclusively in docker, and I could see a requirement / demand for a micro-service to live in it's own docker container. 

Alternatively, couldn't you use a websocket controller and use namespaces and therefore not need ports at all ? That is each microservice connects to the "master" socket 

I am somewhat nervous about the proliferation of ports as the allocation of them can often leave to conflicts. As developers, we tend to choose patterns when selecting port ranges (for example, I used to use 22000-> and port conflicts are such a bastard to deal with

**Comment by jonathan-casarrubias** [comment]
@jmls thanks for sharing your concerns.

**Does each micro-service live on the same machine then ?**
Not necessarily, with OnixJS you have the ability to actually decide between having those in the same machine or not.

1.- If you choose to have those in a same machine, these can communicate over OS IO streams.
2.- If you choose to have those in separated machines, these can communicate using the OnixJS Client.

The SDK is not exclusive to "front-end" applications, that is why I'm only using the concept Client Application, because even other SOA Services are able to use it to call other services in other machines.

**Alternatively, couldn't you use a WebSocket controller and use namespaces and therefore not need ports at all?** Using a ServiceHost as proxy would be kind of anti-pattern, it would create a bottleneck effect and would aggregate latency to every call.

But from your comment, I believe that I can definitely improve the service's registration to make it even more transparent for end developers.

**Comment by jmls** [comment]
so, you dropped a little thing in there ...

"1.- If you choose to have those in a same machine, these can communicate over OS IO streams and not the network. (Implemented but not yet documented)"

does this mean that a micro-service does *not* need a port if they are on the same "machine/container" ? :)

**Comment by jonathan-casarrubias** [comment]
@jmls yes exactly, and you would communicate your micro-services over a RPC API that uses IO Streams instead of WebSockets, that is already built and published, I will document that ASAP...

**Comment by jmls** [comment]
that's way cool. Removes that large concern of mine. If we are running micro-services on docker / k8s then we can default to ports, otherwise to the io streams. thanks for the enlightenment

**Comment by jonathan-casarrubias** [comment]
Cool I'm glad we talked about this, because this was a design from the very beginning in spirit of avoiding network latency, when communicating between micro-services.

I didn't expect someone would also see value  in that feature because that would allow to not to use ports..

Well I think it was a double win, because it solves both problems... No network latency and No required ports.

Any further question or comment I'll be glad to clarify.

Cheers
Jon
